# https://github.com/powerline/fonts#quick-installation
---

- name: "Clone the repo"
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ root_dir }}/.tmp"
    depth: 1
    clone: yes
    update: yes

- name: "Install the fonts"
  shell: "cd {{ root_dir }}/.tmp && ./install.sh"

- name: "Ensure config directory exists"
  file:
    src: "{{ root_dir }}/.config/fontconfig/conf.d"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    state: directory

- name: "Rebuild font cache"
  command: "fc-cache -vf"
