# https://github.com/powerline/fonts#quick-installation
---
- name: "Ensure powerline-fonts source directory exists"
  file:
    path: "{{ powerline_font_src_path }}"
    state: directory
    owner: root
    group: root
  become: yes
  tags:
    - directory

- name: "Ensure powerline-fonts src is fresh"
  git:
    repo: https://github.com/powerline/fonts.git
    dest: "{{ powerline_font_src_path }}"
    clone: yes
    update: yes
  register: powerline_fonts
  tags:
    - repo
