---
- name: "Ensure installers directory is present"
  file:
    path: "{{ rustup_src_path | dirname }}"
    state: directory
    owner: root
    group: root
  become: yes
  tags:
    - directory

- name: "Get latest Rust installer"
  get_url:
    url: https://static.rust-lang.org/rustup.sh
    dest: "{{ rustup_src_path }}"
    mode: "u=rwx,go="
    owner: root
    group: root
  become: yes
  register: rust_installer
  tags:
    - install

- name: "Run latest Rust installer"
  command: "bash {{ rustup_src_path }}"
  become: yes
  when: rust_installer|changed
  tags:
    - compile

- name: "Install Rust packages"
  command: "/usr/local/bin/cargo install --force {{ item }}"
  become: no
  with_items: "{{ rust_packages }}"
  when: rust_installer|changed
  tags:
    - dependency
    - install
    - rust
