---
- name: "Install tmux dependencies"
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ dependencies }}"
  become: yes

- name: "Update tmux"
  package:
    name: "tmux"
    state: "latest"

- name: "Update local code"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ root_dir }}/.tmux/plugins/tpm"
    clone: yes
    update: yes

- name: "Template the config file"
  template:
    src: "home/.tmux.conf"
    dest: "{{ root_dir }}/.tmux.conf"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    mode: "u=rwx"
