---
- name: "Install dev prereqs"
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - "gcc-c++"
    - "make"

- name: "Refresh the Yarn repo"
  get_url:
    url: https://dl.yarnpkg.com/rpm/yarn.repo
    dest: /etc/yum.repos.d/yarn.repo
  become: yes

- name: "Ensure installers directory is present"
  file:
    path: "{{ root_dir }}/.config/installers"
    state: directory
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"

- name: "Get latest Node installer"
  get_url:
    url: https://rpm.nodesource.com/setup_9.x
    dest: "{{ root_dir }}/.config/installers/nodesource"
    mode: "u=rwx,go="
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
  register: nodesource_installer

- name: "Run latest NodeSource installer"
  command: "bash {{ root_dir }}/.config/installers/nodesource"
  become: yes
  when: nodesource_installer|changed

- name: Update main binaries
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - nodejs
    - yarn

