---
- name: "Install git dependencies"
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ dependencies }}"
  become: yes
  tags:
    - dependency
    - install

- name: "Template the config file"
  template:
    src: "home/gitconfig"
    dest: "{{ root_dir }}/.gitconfig"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    mode: "u=rwx"
  tags:
    - config
    - template
