---
- name: "Template the config file"
  template:
    src: "{{ template_path }}"
    dest: "{{ template_root }}/{{ template_path }}"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    mode: "u=rwx,g=r"
  tags:
    - config
    - template
