---
- name: "Template the config file"
  template:
    src: "home/config/terminator/config"
    dest: "{{ config_dir }}/terminator/config"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    mode: "u=rwx"
  tags:
    - config
    - template
