---
- name: "Check tmux"
  include_role:
    name: repo_installer
  vars:
    remote_url: https://github.com/tmux/tmux
    src_path: "{{ tmux_src_path }}"

- name: "Rebuild tmux"
  block:
    - command: "sh autogen.sh"
      args:
        chdir: "{{ tmux_src_path }}"
    - command: "./configure"
      args:
        chdir: "{{ tmux_src_path }}"
    - command: "make"
      args:
        chdir: "{{ tmux_src_path }}"
  when: repo_update|changed
  become: yes
  tags:
    - compile

- name: "Reinstall tmux"
  command: "make install"
  args:
    chdir: "{{ tmux_src_path }}"
  when: repo_update|changed
  become: yes
  tags:
    - install

- name: "Ensure tpm is up-to-date"
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ config_dir }}/tmux/plugins/tpm"
    clone: yes
    update: yes
  tags:
    - repo

- name: "Template the config file"
  template:
    src: "home/.tmux.conf"
    dest: "{{ root_dir }}/.tmux.conf"
    owner: "{{ owning_user }}"
    group: "{{ owning_group }}"
    mode: "u=rwx"
  tags:
    - config
    - template
