---

- include_tasks: windows.yml
  when: ansible_distribution|regex_search('([mM]icrosoft|[wW]indows)')

- include_tasks: not_windows.yml
  when: not ansible_distribution|regex_search('([mM]icrosoft|[wW]indows)')
